# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^docs/
      - id: trailing-whitespace
        exclude: ^docs/
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: mixed-line-ending
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.11.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.4
    hooks:
      - id: pylint
        exclude: ^docs/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812' # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        exclude: ^docs/
